baseURL = 'https://www.mdekort.nl/'
languageCode = 'en-us'
title = 'mdekort.nl'
enableRobotsTXT = true
relativeURLS = true

[params]
  author = 'Melvyn de Kort'
  description = 'Main website'
  year = 2023
  sourceCode = 'https://github.com/melvyndekort/mdekort-nl'

[module]
  [[module.imports]]
    path = "github.com/melvyndekort/dracula-hugo-theme"
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"
